export { SlideManager } from './SlideManager';
export { OpeningSlide } from './OpeningSlide';
export { BusinessProcessSlide } from './BusinessProcessSlide';
export { TechnicalArchitectureSlide } from './TechnicalArchitectureSlide';
export { ImplementationPlanSlide } from './ImplementationPlanSlide';
export { CostEstimateSlide } from './CostEstimateSlide';
export { CostCalculator } from './CostCalculator';
export { CostVisualizationCharts } from './CostVisualizationCharts';
export { ClosingSlide } from './ClosingSlide';
export { AWSArchitectureDiagram } from './AWSArchitectureDiagram';
export { VirtualHighlighter } from './VirtualHighlighter';
export { HighlighterToggle } from './HighlighterToggle';
export { HighlighterManager } from './HighlighterManager';
export { SlideProvider, useSlideContext } from '../contexts/SlideContext';
export { HighlighterProvider, useHighlighter } from '../contexts/HighlighterContext';
export type { SlideConfig, SlideContextType, SlideState, PresentationConfig } from '../types/slide';
export type { HighlightData, SelectionData, HighlighterState } from '../types/highlighter';